# Generated by Django 4.0.5 on 2022-07-31 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeptManagement', '0003_transaction_due_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_to',
            field=models.DateField(default=datetime.date(2022, 7, 31)),
        ),
    ]
